sudo: required

services:
  - docker

before_install:
  - docker build -t nraval1729/complex-docker-react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true nraval1729/complex-docker-react-test npm run test

after_success:
  - docker build -t nraval1729/complex-server ./server
  - docker build -t nraval1729/complex-client ./client
  - docker build -t nraval1729/complex-worker ./worker
  - docker build -t nraval1729/complex-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nraval1729/complex-server
  - docker push nraval1729/complex-client
  - docker push nraval1729/complex-worker
  - docker push nraval1729/complex-nginx
